server {
    listen 80;
    listen [::]:80;
    server_name mcseamnko-design.pp.ua;

    client_max_body_size 64M;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location / {
        return 301 https://mcseamnko-design.pp.ua$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name mcseamnko-design.pp.ua;

    client_max_body_size 64M;

    ssl_certificate /etc/letsencrypt/live/mcseamnko-design.pp.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mcseamnko-design.pp.ua/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        proxy_pass http://127.0.0.1:8082;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_redirect off;
    }
}
